### ISSUE TITLE
Optimise and refresh operator

### ISSUE THREAD

**Issue by agouy** [tercen/scale_operator#3]
* Performance optimisation: use data.table instead of dplyr? Some options: use lazy_dt (see mean_operator), tidytable, or just data.table
* Rename output variable to "value"
* Regenerate tests
* Upgrade ctx$op.value calls and tercen R package

Operator design:
* Computation done per cell (.ci, .ri)
* scale performed row-wise (we scale observations (columns) independently for each variable, i.e. row)

**Comment by tsmonteiro** [comment]
All points addressed in version 0.11.0. Using data.table directly cut the running time in about 2/3 for 100000 observations of 100 variables.

**Comment by agouy** [comment]
Great news, thanks @tsmonteiro.
@makostadima , an optimised version of the operator is ready to be tested (equivalent to the "z score scaling" operator, provided that the "scale" and "center" settings are true (default)

**Comment by makostadima** [comment]
@tsmonteiro and @agouy thank you for the update.
